#database
spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/school_manage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: kiru
    password: a123456789
    driver-class-name:  com.p6spy.engine.spy.P6SpyDriver
  servlet:
     multipart:
        max-file-size: 5MB
  jackson:
    serialization:
      write-dates-as-timestamps: true

mybatis:
  mapperLocations: classpath:mapper/*.xml

server:
  port: 8083
